config/routes.rb
Rails.application.routes.draw do
  root 'services#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :hirers
  resources :suppliers
  resources :services
  resources :budgets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'hire/:service_id' => 'services#hire', as: :hire
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    @budgets = Budget.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)

  end

  # GET /services/1/edit
  def edit
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @supplier = Supplier.where(:id => current_user.id).first
    if @supplier.nil?
      @supplier = Supplier.create(:id => current_user.id, :name => current_user.name, :address => current_user.address)
    end
    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)

  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)

  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)

  end

  def hire

    @budget = Budget.create(
      :requested_service => params[:service_type],
      :hirer_id => current_user.id,
      :hirer_name => current_user.name,
      :supplier_id => params[:supplier_id],
      :supplier_name => params[:supplier_name],
      :budget_status => "Aguardando fornecedor",
      :budget_price => params[:service_price],
      :days_of_service => "Aguardando fornecedor",
      :aditional_information => params[:aditional_information],
     )
    @budget.save

    @hirer = Hirer.create(:id => current_user.id, :name => current_user.name, :address => current_user.address)
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)
    redirect_to services_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:service_type, :hirer_id, :hirer_name, :supplier_id, :supplier_name, :service_status, :service_price, :aditional_information)
    end


end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :tipo_de_serviço %>
      <%= f.text_field :service_type %>
    </div>

    <div class="field">
      <%= f.label :status_do_serviço %>
      <%= f.text_field :service_status, :value => "Aguardando contratação", :readonly => true %>
    </div>

    <div class="field">
      <%= f.label :id_fornecedor %>
      <%= f.text_field :supplier_id, :value => current_user.id, :readonly => true %>
    </div>

    <div class="field">
      <%= f.label :nome_fornecedor %>
      <%= f.text_field :supplier_name, :value => current_user.name, :readonly => true %>
    </div>

    <div class="field">
      <%= f.label :preço_diário %>
      <%= f.text_field :service_price %>
    </div>


    <div class="field">
      <%= f.label :informações_adicionais %>
      <%= f.text_field :aditional_information %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Mostrar', @service %> |
<%= link_to 'Voltar', services_path %>

app/views/services/hire.html.erb
<p>
  <strong>Service type:</strong>
  <%= @service.service_type %>
</p>

<p>
  <strong>Service id:</strong>
  <%= @service.id %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @service.supplier_id %>
</p>

<p>
  <strong>Supplier name:</strong>
  <%= @service.supplier_name %>
</p>

<p>
  <strong>Service status:</strong>
  <%= @service.service_status %>
</p>

<p>
  <strong>Service price:</strong>
  <%= @service.service_price %>
</p>

<p>
  <strong>Aditional Information:</strong>
  <%= @service.aditional_information %>
</p>

<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<h1>Bem Vindo à EHSFeelGood! O que você deseja?</h1>
<h2>Meus Serviços Oferecidos:</h2>
  <table>
    <thead>
      <tr>
        <th>Tipo de Serviço</th>
        <th>Id do Serviço</th>
        <th>Fornecedor</th>
        <th>Nome do Fornecedor</th>
        <th>Status do Serviço</th>
        <th>Preço por dia de Serviço</th>
        <th>Informações Adicionais</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <% if service.supplier_id == current_user.id.to_s%>
          <tr>
            <td><%= service.service_type %></td>
            <td><%= service.id %></td>
            <td><%= service.supplier_id %></td>
            <td><%= service.supplier_name %></td>
            <td><%= service.service_status %></td>
            <td><%= service.service_price %></td>
            <td><%= service.aditional_information %></td>
            <td><%= link_to 'Mostrar', service %></td>
            <td><%= link_to 'Editar', edit_service_path(service) %></td>
            <td><%= link_to 'Deletar', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<%= link_to 'Oferecer Novo Serviço', new_service_path %>

<h1>Deseja ver seus orçamentos? Visite o link abaixo!</h1>

<%= link_to 'Meus Orçamentos', budgets_path %>


<h1>Deseja contratar um serviço? Procure o que deseja abaixo!</h1>
<h2>Serviços Oferecidos:</h2>
  <table>
    <thead>
      <tr>
        <th>Tipo de Serviço</th>
        <th>Id do Serviço</th>
        <th>Fornecedor</th>
        <th>Nome do Fornecedor</th>
        <th>Status do Serviço</th>
        <th>Preço por dia de Serviço</th>
        <th>Informações Adicionais</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <% if service.supplier_id != current_user.id.to_s%>
          <tr>
            <td><%= service.service_type %></td>
            <td><%= service.id %></td>
            <td><%= service.supplier_id %></td>
            <td><%= service.supplier_name %></td>
            <td><%= service.service_status %></td>
            <td><%= service.service_price %></td>
            <td><%= service.aditional_information %></td>
            <td><%= link_to 'Pedir orçamento', new_budget_path(
            :requested_service => service.service_type,
            :supplier_id => service.supplier_id,
            :supplier_name => service.supplier_name,
            :budget_price => service.service_price
            ) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

app/views/services/new.html.erb
<h1>Novo Serviço</h1>

<%= render 'form', service: @service %>

<%= link_to 'Voltar', services_path %>

app/views/services/show.html.erb
<p>
  <strong>Tipo de Serviço:</strong>
  <%= @service.service_type %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @service.supplier_id %>
</p>

<p>
  <strong>Nome do Fornecedor:</strong>
  <%= @service.supplier_name %>
</p>

<p>
  <strong>Status do Serviço:</strong>
  <%= @service.service_status %>
</p>

<p>
  <strong>Service price:</strong>
  <%= @service.service_price %>
</p>

<p>
  <strong>Informações Adicionais:</strong>
  <%= @service.aditional_information %>
</p>

<%= link_to 'Editar', edit_service_path(@service) %> |
<%= link_to 'Voltar', services_path %>