config/routes.rb
Rails.application.routes.draw do
  root 'services#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :hirers
  resources :suppliers
  resources :services
  resources :budgets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'hire/:service_id' => 'services#hire', as: :hire
end

app/models/hirer.rb
class Hirer < ApplicationRecord
end

app/controllers/hirers_controller.rb
class HirersController < ApplicationController
  before_action :set_hirer, only: [:show, :edit, :update, :destroy]

  # GET /hirers
  # GET /hirers.json
  def index
    @hirers = Hirer.all
  end

  # GET /hirers/1
  # GET /hirers/1.json
  def show
  end

  # GET /hirers/new
  def new
    @hirer = Hirer.new
  end

  # GET /hirers/1/edit
  def edit
  end

  # POST /hirers
  # POST /hirers.json
  def create
    @hirer = Hirer.new(hirer_params)

    respond_to do |format|
      if @hirer.save
        format.html { redirect_to @hirer, notice: 'Hirer was successfully created.' }
        format.json { render :show, status: :created, location: @hirer }
      else
        format.html { render :new }
        format.json { render json: @hirer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hirers/1
  # PATCH/PUT /hirers/1.json
  def update
    respond_to do |format|
      if @hirer.update(hirer_params)
        format.html { redirect_to @hirer, notice: 'Hirer was successfully updated.' }
        format.json { render :show, status: :ok, location: @hirer }
      else
        format.html { render :edit }
        format.json { render json: @hirer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hirers/1
  # DELETE /hirers/1.json
  def destroy
    @hirer.destroy
    respond_to do |format|
      format.html { redirect_to hirers_url, notice: 'Hirer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hirer
      @hirer = Hirer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hirer_params
      params.require(:hirer).permit(:name, :address)
    end
end

app/helpers/hirers_helper.rb
module HirersHelper
end

app/views/hirers/_form.html.erb
<%= form_for(hirer) do |f| %>
  <% if hirer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hirer.errors.count, "error") %> prohibited this hirer from being saved:</h2>

      <ul>
      <% hirer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hirers/edit.html.erb
<h1>Editing Hirer</h1>

<%= render 'form', hirer: @hirer %>

<%= link_to 'Show', @hirer %> |
<%= link_to 'Back', hirers_path %>

app/views/hirers/index.html.erb
<h1>Hirers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hirers.each do |hirer| %>
      <tr>
        <td><%= hirer.name %></td>
        <td><%= hirer.address %></td>
        <td><%= link_to 'Show', hirer %></td>
        <td><%= link_to 'Edit', edit_hirer_path(hirer) %></td>
        <td><%= link_to 'Destroy', hirer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hirer', new_hirer_path %>

app/views/hirers/new.html.erb
<h1>New Hirer</h1>

<%= render 'form', hirer: @hirer %>

<%= link_to 'Back', hirers_path %>

app/views/hirers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @hirer.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hirer.address %>
</p>

<%= link_to 'Edit', edit_hirer_path(@hirer) %> |
<%= link_to 'Back', hirers_path %>