config/routes.rb
Rails.application.routes.draw do
  root 'services#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :hirers
  resources :suppliers
  resources :services
  resources :budgets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'hire/:service_id' => 'services#hire', as: :hire
end

app/models/budget.rb
class Budget < ApplicationRecord
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)

  end

  # GET /budgets/1/edit
  def edit
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    @user.update_attribute(:number_of_transactions, new_number_of_transactions)

  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)
    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)

  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
    @user = User.where(:id => current_user.id).first
    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)

    new_number_of_transactions = @user.number_of_transactions.nil? ? 1:(@user.number_of_transactions + 1)
    @user.update_attribute(:number_of_transactions, new_number_of_transactions)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:requested_service, :hirer_id, :hirer_name, :supplier_id, :supplier_name, :budget_status, :budget_price, :aditional_information)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_for(budget) do |f| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :serviço_requisitado %>
    <%= f.text_field :requested_service, :value => params['requested_service'], :readonly => true %>

  </div>

  <div class="field">
    <%= f.label :id_do_contratante %>
    <%= f.text_field :hirer_id, :value => current_user.id, :readonly => true %>
  </div>

  <div class="field">
    <%= f.label :nome_do_contratante %>
    <%= f.text_field :hirer_name, :value => current_user.name, :readonly => true %>
  </div>

  <div class="field">
    <%= f.label :id_do_fornecedor %>
    <%= f.text_field :supplier_id, :value => params['supplier_id'], :readonly => true %>
  </div>

  <div class="field">
    <%= f.label :nome_do_fornecedor %>
    <%= f.text_field :supplier_name, :value => params['supplier_name'], :readonly => true %>
  </div>

  <div class="field">
    <%= f.label :status_do_orçamento %>
    <%= f.text_field :budget_status, :value => 'Aguardando fornecedor', :readonly => params['supplier_id'] == current_user.id ? false : true %>
  </div>

  <div class="field">
    <%= f.label :preço_por_dia %>
    <%= f.text_field :budget_price, :value => params['budget_price'], :readonly => params['supplier_id'] == current_user.id ? false : true %>
  </div>

  <div class="field">
    <%= f.label :dias_de_serviço %>
    <%= f.text_field :days_of_service, :value => params['days_of_service'], :readonly => params['supplier_id'] == current_user.id ? false : true  %>
  </div>

  <div class="field">
    <%= f.label :informações_adicionais %>
    <%= f.text_field :aditional_information %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editar Orçamento</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Mostrar', @budget %> |
<%= link_to 'Voltar', services_path %>

app/views/budgets/index.html.erb
<h1>Meus Orçamentos</h1>

<table>
  <thead>
    <tr>
      <th>Serviço Requisitado</th>
      <th>Contratante</th>
      <th>Nome do Contratante</th>
      <th>Fornecedor</th>
      <th>Nome do Fornecedor</th>
      <th>Status do Orçamento</th>
      <th>Preço por Dia</th>
      <th>Dias de Serviço</th>
      <th>Informações Adicionais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @budgets.each do |budget| %>
        <tr>
          <% if budget.supplier_id == current_user.id.to_s || budget.hirer_id == current_user.id.to_s%>
            <td><%= budget.requested_service %></td>
            <td><%= budget.hirer_id %></td>
            <td><%= budget.hirer_name %></td>
            <td><%= budget.supplier_id %></td>
            <td><%= budget.supplier_name %></td>
            <td><%= budget.budget_status %></td>
            <td><%= budget.budget_price %></td>
            <td><%= budget.days_of_service %></td>
            <td><%= budget.aditional_information %></td>
            <td><%= link_to 'Mostrar', budget %></td>
            <td><%= link_to 'Editar', edit_budget_path(budget) %></td>
            <td><%= link_to 'Recusar', budget, method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Voltar', services_path %>

app/views/budgets/new.html.erb
<h1>Novo Orçamento</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Voltar', budgets_path %>

app/views/budgets/show.html.erb
<p>
  <strong>Pedido:</strong>
  <%= @budget.requested_service %>
</p>

<p>
  <strong>Contratante:</strong>
  <%= @budget.hirer_id %>
</p>

<p>
  <strong>Nome do Contratante:</strong>
  <%= @budget.hirer_name %>
</p>

<p>
  <strong>Fornecedor:</strong>
  <%= @budget.supplier_id %>
</p>

<p>
  <strong>Nome do Fornecedor:</strong>
  <%= @budget.supplier_name %>
</p>

<p>
  <strong>Status do Orçamento:</strong>
  <%= @budget.budget_status %>
</p>

<p>
  <strong>Preço por Dia:</strong>
  <%= @budget.budget_price %>
</p>

<p>
  <strong>Dias de Serviço:</strong>
  <%= @budget.days_of_service %>
</p>

<p>
  <strong>Informações Adicionais:</strong>
  <%= @budget.aditional_information %>
</p>

<%= link_to 'Editar', edit_budget_path(@budget) %> |
<%= link_to 'Voltar', budgets_path %>